# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: getprice
# app and org for use with dashboard.serverless.com
app: bitcoinprice
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  # you can overwrite defaults here
  stage: dev
  region: us-east-1

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

# you can define service wide environment variables here
# environment:
# variable1: value1

functions:
  getPrice:
    handler: api/handler.price
    memorySize: 128
    description: Get latest bitcoin price from DB.
    events:
      - http:
          path: price
          method: get

  getPriceHandler:
    handler: get_price_worker.getPrice
    memorySize: 512
    description: Get latest bitcoin price from bitfinex.
    events:
      # Invoke Lambda function every 12 hours
      # Avoids exhausting free-tier resources by reducing hits to lambda functions
      - schedule: rate(12 hours)

resources: # CloudFormation template syntax from here on.
  Resources:
    priceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: prices_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
